---
# tasks file for dotbash
- name: "Including Env Setup"
  ansible.builtin.include_tasks: env_setup.yml

- name: "Including Installation"
  ansible.builtin.include_tasks: install.yml

- name: Including bash settings
  ansible.builtin.import_tasks: bash_setup.yml
